todo-aspnetmvc/Models/FolderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using todo_domain_entities.Models;

namespace todo_aspnetmvc.Models
{
    public class FolderViewModel
    {
        public Guid Id { get; set; }
        [Required] public string Name { get; set; }
        public bool IsHidden { get; set; }
        public string? Icon { get; set; }
        public List<ItemViewModel> Items { get; set; } = new List<ItemViewModel>();
    }
}

todo-aspnetmvc/Models/ItemFilterParameters.cs
using System;
using todo_domain_entities.Models;

namespace todo_aspnetmvc.Models
{
    public class ItemFilterParameters : SortParameters
    {
        public string? Name { get; set; }
        public bool IsHidden { get; set; }
        public StatusItem? Status { get; set; }
        
        public DateTime? CompletionDate{ get; set; }
       
    }
}

todo-aspnetmvc/Models/ItemViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using todo_domain_entities.Models;

namespace todo_aspnetmvc.Models
{
    public class ItemViewModel
    {
        public Guid Id { get; set; }

        [Required] public string Name { get; set; }
        public string? Description { get; set; }
        public StatusItem Status { get; set; }
        public DateTime? StartDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime? CompletionDate { get; set; }

        public Guid FolderId { get; set; }
        public FolderViewModel? Folder { get; set; }
    }
}

todo-aspnetmvc/Models/UpdateTaskViewModel.cs
using System;
using todo_domain_entities.Models;

namespace todo_aspnetmvc.Models
{
    public class UpdateTaskViewModel
    {
        public Guid FolderId { get; set; }
        public StatusItem Status { get; set; }
    }
}

todo-aspnetmvc/Controllers/FoldersController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using todo_aspnetmvc.Services;
using todo_domain_entities.Models;
using todo_aspnetmvc.Models;

namespace todo_aspnetmvc.Controllers
{
    public class FoldersController : Controller
    {
        private readonly IFolderService _foldersService;

        public FoldersController(IFolderService foldersService)
        {
            _foldersService = foldersService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(bool isHidden = false)
        {
            var folder = await _foldersService.GetFolders(new ItemFilterParameters {IsHidden = isHidden});
            return View(folder);
        }

        [HttpGet("{folderId:guid}")]
        public async Task<IActionResult> Get([FromRoute] Guid folderId)
        {
            FolderViewModel findTask = await _foldersService.GetFolder(folderId);

            return View(findTask);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? folderId)
        {
            if (folderId.HasValue)
            {
                FolderViewModel findTask = await _foldersService.GetFolder(folderId.Value);
                return View(findTask);
            }

            return View(new FolderViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Save([FromForm] FolderViewModel folder)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", folder);
            }

            if (folder.Id == Guid.Empty)
            {
                folder.Id = await _foldersService.Create(folder);
            }
            else
            {
                await _foldersService.Update(folder.Id, folder);
            }

            return RedirectToAction("Get", "Folders", new {folderId = folder.Id});
        }

        [HttpPost]
        public async Task<IActionResult> Copy(Guid folderId)
        {
            var newFolderId = await _foldersService.Copy(folderId);
            return RedirectToAction("Get", "Folders", new {folderId = newFolderId});
        }

        [HttpPost("{folderId:guid}")]
        public async Task<IActionResult> DeleteList([FromRoute] Guid folderId)
        {
            await _foldersService.Delete(folderId);
            return RedirectToAction("Index", "Folders");
        }
    }
}

todo-aspnetmvc/Controllers/ItemsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using todo_aspnetmvc.Models;
using todo_aspnetmvc.Services;

namespace todo_aspnetmvc.Controllers
{
    [Route("[controller]/[action]")]
    public class ItemsController : Controller
    {
        private readonly IItemService _itemsService;

        public ItemsController(IItemService itemsService)
        {
            _itemsService = itemsService;
        }

        [HttpGet]
        public async Task<IActionResult> GetTodayItems()
        {
            var findTask = await _itemsService.GetTodayItems();
            return View(findTask);
        }

        public async Task<IActionResult> EditItem(Guid? taskId, Guid? folderId)
        {
            if (taskId.HasValue)
            {
                var task = await _itemsService.GetItem(taskId.Value);
                return View(task);
            }

            return View(new ItemViewModel {FolderId = folderId.Value});
        }

        [HttpPost]
        public async Task<IActionResult> SaveTask([FromForm] ItemViewModel task)
        {
            if (!ModelState.IsValid)
            {
                return View("EditItem", task);
            }

            if (task.Id == Guid.Empty)
            {
                task.Id = await _itemsService.Create(task);
                return RedirectToAction("Get", "Folders", new {folderId = task.FolderId});
            }

            var taskEntity = await _itemsService.GetItem(task.Id);
            taskEntity.Name = task.Name;
            taskEntity.Description = task.Description;
            taskEntity.CompletionDate = task.CompletionDate;

            await _itemsService.Update(taskEntity);
            return RedirectToAction("Get", "Folders", new {folderId = taskEntity.FolderId});
        }

        [HttpPost("{taskId:guid}")]
        public async Task<IActionResult> UpdateStatus([FromRoute] Guid taskId, [FromForm] UpdateTaskViewModel viewModel)
        {
            await _itemsService.UpdateStatus(taskId, viewModel.Status);
            return Ok();
        }

        /// <summary>
        /// Method deletes task by Id
        /// </summary>
        /// <param name="taskId"></param>
        /// <returns></returns>
        [HttpPost("{taskId:guid}")]
        public async Task<IActionResult> DeleteTask([FromRoute] Guid taskId)
        {
            var task = await _itemsService.GetItem(taskId);
            await _itemsService.Delete(taskId);
            return RedirectToAction("Get", "Folders", new {folderId = task.FolderId});
        }
    }
}

todo-aspnetmvc/Views/Folders/Edit.cshtml
@model todo_aspnetmvc.Models.FolderViewModel

@{
    ViewBag.Title = Model.Id == Guid.Empty ? "Add list" : "Edit list";
    Layout = "_Layout";
}

@using (Html.BeginForm("Save", "Folders", FormMethod.Post))
{
    <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">
    <div class="modal-body">

        <div class="mb-3">
            @Html.LabelFor(x => x.Name, new {htmlAttributes = new {@class = "form-label"}})
            @Html.EditorFor(x => x.Name, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(x => x.Name)
        </div>
        <div class="mb-3">
            <label for="chooseIcon" class="form-label">Icon</label>
            <select class="form-select" aria-label="Default select example" id="chooseIcon" name="Icon">
                <option value="img/no-pictures.png">no picture</option>
                <option value="img/calendar.png">calendar</option>
                <option value="img/person.png">person</option>
                <option value="img/today.png">today</option>
            </select>

        </div>
        <div class="mb-3">
            <label>Hidden</label>
            @Html.CheckBox("IsHidden", @Model.IsHidden)
        </div>
    </div>
    <div class="modal-footer">
        @if (Model.Id == Guid.Empty)
        {
            <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Folders")'">Back</button>
        }
        else
        {
            <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Get", "Folders", new {folderId = @Model.Id})'">Back</button>
        }
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
}

todo-aspnetmvc/Views/Folders/Get.cshtml
@model todo_aspnetmvc.Models.FolderViewModel
@using todo_domain_entities.Models;

@{
    ViewBag.Title = "List";
    Layout = "_Layout";
}

<div class="card navbar" style="">
    <ul class="list-group list-group-flush">
        <div class="btn-group" role="group" aria-label="Basic example">
            <div class="btn-group" role="group" aria-label="Basic example">
                <button onclick="location.href='@Url.Action("EditItem", "Items", new {folderId = Model.Id})'" class="btn btn-outline-primary" type="button">Add task</button>
            </div>
            <button type="submit" class="btn btn-outline-primary" onclick="location.href='@Url.Action("Edit", "Folders", new {folderId = Model.Id})'">Edit list</button>
            @using (Html.BeginForm("Copy", "Folders", new {folderId = Model.Id}))
            {
                <button type="submit" class="btn btn-outline-primary">
                    Copy list
                </button>
            }
            @using (Html.BeginForm("DeleteList", "Folders", new {folderId = Model.Id}))
            {
                <button type="submit" name="X-HTTP-Method-Override" value="DELETE" class="btn btn-outline-primary cancel" formnovalidate
                        onclick="return confirm('Are you sure?')">
                    Delete
                </button>
            }
            <button type="button" class="btn btn-outline-primary" onclick="location.href='@Url.Action("Index", "Folders")'">Back</button>
        </div>

    </ul>

    <div class="card-header">
        <img src=@Model.Icon alt="..." class="img-circle">
        @Model.Name
    </div>

    <ol class="list-group list-group">
        @foreach (var i in Model.Items.Where(x => x.Status == StatusItem.NotStarted))
        {
            <li class="list-group-item d-flex justify-content-between align-items-start ">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">
                        <input id="cb-@i.Id" task-id="@i.Id" list-id="@i.Folder" class="form-check-input me-1 task-item" type="checkbox" @(i.Status == StatusItem.Completed ? "checked" : "")>
                        @i.Name
                    </div>
                    <div class="fw-gray">
                        @(i.CompletionDate != null ? "Completion date:" : "")
                        @i.CompletionDate?.ToString("dd.MM.yyyy")
                    </div>
                </div>
                <ul class="ul-w">
                    <li>
                        <button onclick="location.href='@Url.Action("EditItem", "Items", new {taskId = i.Id})'" class="badge bg-primary rounded-pill task-button">Edit</button>
                    </li>
                    <li>
                        @using (Html.BeginForm("DeleteTask", "Items", new {taskId = @i.Id}, FormMethod.Post))
                        {
                            <button type="submit" name="X-HTTP-Method-Override" value="DELETE" class="badge bg-primary rounded-pill task-button cancel" formnovalidate
                                    onclick="return confirm('Are you sure?')">
                                Delete
                            </button>
                        }
                    </li>
                </ul>
            </li>
        }
    </ol>

    <ol class="list-group list-group">
        @foreach (var i in Model.Items.Where(x => x.Status == StatusItem.Completed))
        {
            <li class="list-group-item d-flex justify-content-between align-items-start ">
                <div class="ms-2 me-auto">
                    <div class="list-gray">
                        <input id="cb-@i.Id" task-id="@i.Id" list-id="@i.Folder" class="form-check-input me-1 task-item" type="checkbox" @(i.Status == StatusItem.Completed ? "checked" : "")>

                        @i.Name
                    </div>
                    <div class="fw-gray">
                        @(i.CompletionDate != null ? "Completion date:" : "")
                        @i.CompletionDate?.ToString("dd.MM.yyyy")
                    </div>
                </div>
                <ul class="ul-w">
                    <li>
                        <button onclick="location.href='@Url.Action("EditItem", "Items", new {taskId = i.Id})'" class="badge bg-primary rounded-pill task-button">Edit</button>
                    </li>
                    <li>
                        @using (Html.BeginForm("DeleteTask", "Items", new {taskId = @i.Id}, FormMethod.Post))
                        {
                            <button type="submit" name="X-HTTP-Method-Override" value="DELETE" class="badge bg-primary rounded-pill task-button cancel" formnovalidate
                                    onclick="return confirm('Are you sure?')">
                                Delete
                            </button>
                        }
                    </li>
                </ul>
            </li>
        }
    </ol>
</div>


@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script>
    $(document).on("click", ".task-item", function(){
        let status = $(this).is(':checked') ? 1 : 0;
        let id = $(this).attr("task-id");
        let folderId = $(this).attr("list-id");
        $.post("/Items/UpdateStatus/"+id, {status: status,FolderId: folderId }, function (json) {
            location.reload();
        });
    });
    </script>


}

todo-aspnetmvc/Views/Folders/Index.cshtml
@model List<todo_aspnetmvc.Models.FolderViewModel>

@{
    ViewBag.Title = "Lists";
    Layout = "_Layout";
}

<div class="lists-container">
    <div class="lists">

        <div class="todo-list" onclick="location.href='@Url.Action("GetTodayItems", "Items")'">
            <div class="list-icon">
                <img src="img/today.png" alt="no picture" class="img-circle">
            </div>
            <div class="list-info">
                <div class="list-head">
                    Today
                </div>
                <div class="list-items-count">
                    @(_itemService.GetTasksCount()) tasks
                </div>
            </div>

        </div>

        @foreach (var p in Model)
        {
            <div class="todo-list" onclick="location.href='@Url.Action("Get", "Folders", new {folderId = p.Id})'">
                <div class="list-icon">
                    @if (!string.IsNullOrEmpty(p.Icon))
                    {
                        <img src=@p.Icon alt="..." class="img-circle">
                    }
                    else
                    {
                        <img src="img/no-pictures.png" alt="no picture" class="img-circle">
                    }
                </div>
                <div class="list-info">
                    <div class="list-head">
                        @p.Name
                    </div>
                    <div class="list-items-count">
                        @p.Items.Count tasks
                    </div>
                </div>
            </div>
        }
        
          <div class="todo-list" onclick="location.href='@Url.Action("Edit", "Folders")'">
              <div class="list-icon img-center" onclick="location.href='@Url.Action("Edit", "Folders")'">
                 <img src="img/plus.png" alt="add list" class="img-circle img-small"> 
            </div>
           
       </div>
        
    </div>
</div>

todo-aspnetmvc/Views/Items/EditItem.cshtml
@model todo_aspnetmvc.Models.ItemViewModel

@{
    ViewBag.Title = Model.Id == Guid.Empty ? "Add task" : "Edit task";
    Layout = "_Layout";
}

@using (Html.BeginForm("SaveTask", "Items", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.FolderId)
    <div class="modal-body">

        <div class="mb-3">
            @Html.LabelFor(x => x.Name, new {htmlAttributes = new {@class = "form-label"}})
            @Html.EditorFor(x => x.Name, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(x => x.Name)

        </div>
        <div class="mb-3">
            <label for="Description" class="form-label">Description</label>
            <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
        </div>

        <div class="mb-3">
            <label for="CompletionDate">CompletionDate</label>
            <input id="CompletionDate" class="form-control" type="date" name="CompletionDate" value="@Model.CompletionDate?.ToString("yyyy-MM-dd")"/>
            <span id="CompletionDateSelected"></span>

        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Get", "Folders", new {folderId = Model.FolderId})'">Back</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
}

todo-aspnetmvc/Views/Items/GetTodayItems.cshtml
@model System.Collections.Generic.List<todo_aspnetmvc.Models.ItemViewModel>
@using todo_domain_entities.Models;

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="card navbar" style="width: 25rem;">


    <div class="btn-group btn-left" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-outline-primary" onclick="location.href='@Url.Action("Index", "Folders")'">Back</button>
    </div>

    <div class="card-header">
        <img src="/img/today.png" alt="today" class="img-circle">
        Today
    </div>

    <ol class="list-group list-group">
        @foreach (var i in Model.Where(x => x.Status == StatusItem.NotStarted))
        {
            <li class="list-group-item d-flex justify-content-between align-items-start ">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">
                        <input id="cb-@i.Id" task-id="@i.Id" list-id="@i.Folder" class="form-check-input me-1 task-item" type="checkbox" @(i.Status == StatusItem.Completed ? "checked" : "")>
                        @i.Name
                    </div>
                    <div class="fw-gray">
                        @(i.CompletionDate != null ? "Completion date:" : "")
                        @i.CompletionDate?.ToString("dd.MM.yyyy")
                    </div>
                </div>
            </li>
        }
        <hr>
    </ol>

    <ol class="list-group list-group">
        @foreach (var i in Model.Where(x => x.Status == StatusItem.Completed))
        {
            <li class="list-group-item d-flex justify-content-between align-items-start ">
                <div class="ms-2 me-auto">
                    <div class="list-gray">
                        <input id="cb-@i.Id" task-id="@i.Id" list-id="@i.Folder" class="form-check-input me-1 task-item" type="checkbox" @(i.Status == StatusItem.Completed ? "checked" : "")>
                        @i.Name
                    </div>
                    <div class="fw-gray">
                        @(i.CompletionDate != null ? "Completion date:" : "")
                        @i.CompletionDate?.ToString("dd.MM.yyyy")
                    </div>
                </div>
            </li>
        }
    </ol>

</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script>
    $(document).on("click", ".task-item", function(){
        let status = $(this).is(':checked') ? 1 : 0;
        let id = $(this).attr("task-id");
        let folderId = $(this).attr("list-id");
        $.post("/Items/UpdateStatus/"+id, {status: status,FolderId: folderId }, function () {
            location.reload();
        });
    });
    </script>
}

todo-aspnetmvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>

<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="@Url.Action("Index", "Folders")">ToDoList <span class="task-count">(Today you have @_itemService.GetTasksCount() tasks)</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Folders", new {isHidden = true})">Show hidden List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="@Url.Action("Edit", "Folders")">Add list</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<div class="">
    @RenderBody()
</div>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>